name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: credit
          POSTGRES_PASSWORD: creditpass
          POSTGRES_DB: creditdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U credit" 
          --health-interval=5s 
          --health-timeout=5s 
          --health-retries=10
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build backend
        working-directory: backend
        run: |
          ./mvnw -q -B -DskipTests=false test package
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/creditdb
          SPRING_DATASOURCE_USERNAME: credit
          SPRING_DATASOURCE_PASSWORD: creditpass
          JWT_SECRET: test-secret
          JWT_EXP_MINUTES: 60

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build 